### ISSUE TITLE
Artwork: create an 'Uncle Sam' like coala poster.

### ISSUE THREAD

**Issue by tulphoon** [coala/meta#57]
We could create an 'Uncle Sam' like poster, but replaced with coala pointing towards the viewer and a phrase like 'coala wants you to lint your code!'. Suggestions highly recommended :)

**Comment by sils** [comment]
CC @beatrix-bodo although she probably lacks time it might be interesting

**Comment by jayvdb** [comment]
Examples at https://commons.wikimedia.org/wiki/Category:Derivative_works_of_I_want_you_for_the_U.S._Army_nearest_recruiting_station

Imo we should stay with 'I want you ..' as the start of the text, otherwise the reference is lost.

A coala pointing is the hard part.
https://commons.wikimedia.org/wiki/Category:Phascolarctos_cinereus
